-- =============================================
-- Migration 016: Cleanup
-- TeamwearOS
-- =============================================
-- Google Drive URL functionality has been removed from the application.
-- This migration is intentionally empty / a no-op.
-- If migration 016 was previously applied (adding google_drive_url to clubs),
-- that column is harmless to leave in place — the app no longer reads or
-- writes it, so no action is required.
-- =============================================
